---
- hosts: localhost
  gather_facts: true
  vars:
    state: "present"
    dotfiles: "{{ ansible_env.HOME }}/.config"
    packages:
      - name: "gcc"
        commands:
          - ln -s /home/linuxbrew/.linuxbrew/bin/gcc-14 /home/linuxbrew/.linuxbrew/bin/gcc

      - name: "npm"

      - name: "neovim"
        bash: 
          - "EDITOR=nvim"

      - name: "fzf"
        bash: 
          - "eval \"$(fzf --bash)\""
          - "alias fzf=\"fzf --reverse\""

      - name: "htop"

      - name: "rsync"

      - name: "lsd"

      - name: "bat"

      - name: "ripgrep"

      - name: "tmux"

      - name: "zoxide"
        bash: 
          - "eval \"$(zoxide init bash)\""

      - name: "delta"

  tasks:
      - name: Install or remove packages
        community.general.homebrew:
          name: "{{ item.name }}"
          state: "{{ state }}"
        loop: "{{ packages }}"

      - name: Modify bashrc
        blockinfile:
          path: "{{ ansible_env.HOME }}/.bashrc"
          append_newline: true
          prepend_newline: true
          marker: "# {mark} {{ item.0.name }} BLOCK"
          block: "{{ item.1 }}"
          state: "{{ state }}"
        loop: "{{ packages|subelements('bash', skip_missing=true) }}"

      - name: Run commands
        shell: "{{ item.1 }}"
        loop: "{{ packages|subelements('commands', skip_missing=true) }}"
        when: state == "present"

      - name: Get dotfile from GIT
        git:
          repo: https://github.com/AaySah92/config_dotfiles.git
          dest: "{{ dotfiles }}"
        when: state == "present"

      - name: Remove dotfile directory
        file:
          path: "{{ dotfiles }}"
          state: absent
        when: state == "absent"
          
        # https://dev.to/cerico/using-brew-in-a-multi-user-system-2lnl
