---
- hosts: localhost
  gather_facts: true
  vars:
    state: "present"
    config_dir: "{{ ansible_env.HOME }}/config"
    nvim_dir: "{{ ansible_env.HOME }}/.config/nvim"
    tmux_dir: "{{ ansible_env.HOME }}/.config/tmux"
    lazyvim_config_dir: "{{ nvim_dir }}/lua/config"
    tpm_config_dir: "{{ tmux_dir }}/plugins/tpm"
    bashrc_entires:
      - package: fzf
        entries:
          - "eval \"$(fzf --bash)\""
          - "alias fzf=\"fzf --reverse\""
      - package: lsd
        entries:
          - "alias ls=\"lsd\""
      - package: nvim
        entries:
          - "export EDITOR=nvim"
      - package: zoxide
        entries:
          - "eval \"$(zoxide init bash)\""
    lazyvim_config_files:
      - autocmds.lua
      - keymaps.lua
      - lazy.lua
      - options.lua
  tasks:
    - name: Setup aliases / environment variables / bash integrations
      blockinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        append_newline: true
        prepend_newline: true
        marker: "# {mark} {{ item.package }} BLOCK"
        block: |
          {% for entry in item.entries %}
            {{ entry }}
          {% endfor %}
        state: "{{ state }}"
      loop: "{{ bashrc_entires }}"

    - name: Configure packages
      block:
        - name: Download configurations
          git:
            repo: https://github.com/AaySah92/config_dotfiles.git
            dest: "{{ config_dir }}"
        - name: Configure neovim (lazyvim)
          block:
            - name: Download lazyvim
              git:
                repo: https://github.com/LazyVim/starter.git
                dest: "{{ nvim_dir }}"
                force: true
            - name: Remove default lazyvim config
              file:
                path: "{{ lazyvim_config_dir }}/{{ item }}"
                state: absent
              loop: "{{ lazyvim_config_files }}"
            - name: Link custom lazyvim config
              file:
                src: "{{ config_dir }}/lazyvim/{{ item }}"
                dest: "{{ lazyvim_config_dir }}/{{ item }}"
                state: link
              loop: "{{ lazyvim_config_files }}"
            - name: Configure tmux
              block:
                - name: Link tmux config
                  file:
                    src: "{{ config_dir }}/tmux"
                    dest: "{{ tmux_dir }}"
                    state: link
                - name: Download tpm
                  git:
                    repo: https://github.com/tmux-plugins/tpm.git
                    dest: "{{ tpm_config_dir }}"
                    force: true
                - name: Install tpm plugins
                  shell: "{{ tpm_config_dir }}/bin/install_plugins"
      when: state == "present"
    - name: Remove configurations
      file:
        path: "{{ config_dir }}"
        state: absent
      when: state == "absent"
        
      # https://dev.to/cerico/using-brew-in-a-multi-user-system-2lnl
      # go 
      # go install gopls
      # starship
      # nerd font
